Задание к уроку Ассоциации моделей
skrepkoed/TestGuru pull request #6
Opened 2021-03-02 18:07 UTC by skrepkoed

2021-03-02 18:55 UTC, BubuntuClu requested changes

2021-03-02 18:55 UTC, BubuntuClu commented on app/models/authorship.rb
> +class Authorship < ApplicationRecord
у одного теста может быть несколько авторов?
если да, то напиши об этом, что ты через такую концепцию будешь делать дальше

если у теста только один автор будет, то эта неправильная связь.

2021-03-02 18:55 UTC, BubuntuClu commented on app/models/test.rb
> +  has_one :user, through: :authorships
чем отличается `users` от `user`? надо задать имя для ассоциации чтобы было понятно что это автор, смотри `class_name` опцию

2021-03-02 18:55 UTC, BubuntuClu commented on app/models/test.rb
> +  has_one :user, through: :authorships
а где подключена эта ассоциация authorships?

2021-03-02 18:55 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests, through: :authorships
две ассоциации с одним именем не будут работать. тут тоже надо задать кастомное имя для ассоциации

2021-03-02 18:55 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins('JOIN tests_users ON tests.id=tests_users.test_id').where('level=? AND user_id=?', level,
`tests.where(level: level)`

2021-03-02 18:55 UTC, BubuntuClu commented on db/migrate/20210302162407_create_join_table_tests_authors.rb
> +    create_table :authorships, id: false do |t|
таблицы без id редко когда стоит создавать

2021-03-03 18:54 UTC, BubuntuClu commented on db/migrate/20210302162407_create_join_table_tests_authors.rb
> +      t.references :user, unique: true, null: false, foreign_key: true
уникальность тут не нужна. получается один юзер может быть только один раз автором.

ты скажи, ты будешь придерживаться этой концепции, что у теста может быть несколько авторов?

2021-03-04 10:40 UTC, skrepkoed commented on db/migrate/20210302162407_create_join_table_tests_authors.rb
> +      t.references :user, unique: true, null: false, foreign_key: true
Нет, я хочу, чтобы был один автор у теста.

2021-03-04 11:08 UTC, skrepkoed commented on db/migrate/20210302162407_create_join_table_tests_authors.rb
> +      t.references :user, unique: true, null: false, foreign_key: true
Теперь вижу проблему: если тест через author= получает нового автора, то автор просто обновляется, но если со стороны пользователя добавить тест себе в авторство через tests_authorships<<, то тест может иметь двух авторов.

2021-03-04 16:11 UTC, merged