Задание к уроку валидации и scope-методы
skrepkoed/TestGuru pull request #7
Opened 2021-03-04 18:58 UTC by skrepkoed

2021-03-05 06:55 UTC, BubuntuClu requested changes

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/question.rb
> +  	errors.add(:answers) unless (1..4).include?(answers.count)
errors.add(:answers) - в это выражение добавь сообщение об ошибке
тут будет просто >4. нижнее значение не надо проверять. 
так же лучше заменить unless на if, так как unless сложнее воспринимать во время чтения кода

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/question.rb
> +  validate :validate_question_number_answers
валидировать стоит только при создании ответа

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/test.rb
> +  	binding.pry
это убьет приложение на проде, нельзя допускать этого в коммиты

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/test.rb
> +  	errors.add(:title)  unless self.class.where('title=? AND level=?',title,level).empty?
используй стандартную валидацию для проверки уникальности

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :tests_by_category, ->(title){joins(:category).where('categories.title=?',title)}
а куда потерялись методы сортировки и выборки?

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/test.rb
>    has_one :author, through: :authorship, source: :user
видел что ты отписал что это неправильно. значит в рамках этой задачи, тебе надо еще переделать эту связь. для реализации автораства не нужна доп таблица

2021-03-05 06:55 UTC, BubuntuClu commented on db/migrate/20210228065412_create_questions.rb
> +      t.references :test, foreign_key: true
миграции, которые уже слиты в мастер нельзя править. все изменения в такой код надо вносить только через новые миграции. это изменения надо удалить из этого файла и создать миграцию которая уберет дефолтные значения

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/test.rb
> +  	errors.add(:title)  unless self.class.where('title=? AND level=?',title,level).empty?
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/user.rb
> +  validates :email, presence:true
отступ

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :level, numericality: {only_intger:true}
отступ

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/answer.rb
> +  validates :body, presence:true
`presence: true`

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/category.rb
> +  validates :title, presence:true
много пробелов съедаешь

2021-03-05 06:55 UTC, BubuntuClu commented on app/models/answer.rb
> +  scope :correct_answers, ->{where(correct:true)}
по руби стилю `{ where(correct:true) }`

2021-03-05 17:33 UTC, BubuntuClu commented on app/models/answer.rb
> +  validate :validate_question_number_answers
валидировать стоит только при создании ответа. не нужна валидация при обновлении/...

2021-03-05 17:33 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :user
назвать лучше ассоциацию `author`, посмотри опцию `class_name`

2021-03-05 17:33 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :tests_by_category, ->(title) { joins(:category).where('categories.title=?', title).order(title: :desc) }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2021-03-05 17:33 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
оставляй пустые строки между логически разными секциями. валидации отдели от скоупов и тд

2021-03-05 17:33 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
`validates :title, presence: true, uniqueness: { scope: :level, message: 'Title and level combinztion must be unique' }`

2021-03-05 17:33 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :tests
тут тоже не понятно что это за тесты. назови `created_tests/authored_tests`

2021-03-06 05:20 UTC, skrepkoed commented on app/models/answer.rb
> +  validate :validate_question_number_answers
Почему не нужна валидация при обновлении? Ведь тогда можно будет сменить question_id и тогда у вопроса будет пять ответов.

2021-03-06 10:18 UTC, merged